#!/bin/bash
set -e

# ============================================================================
# Deploy the five per-position agents to Bedrock AgentCore.
#
#   AWS_DEFAULT_REGION=us-east-1 ./deploy-all.sh            # all five
#   AWS_DEFAULT_REGION=us-east-1 ./deploy-all.sh ai-gk      # just one
#
# Each agent is staged into _build/<agent>/ with the shared lib/ copied in, so
# lib/ stays a single source of truth and is never duplicated in the tree.
#
# AFC_* settings are baked into each bundle: a deployed runtime does NOT inherit
# the shell that deployed it, so anything exported here would otherwise be lost
# and silently revert to defaults.
#
# Prerequisites:
#   pip install bedrock-agentcore-starter-toolkit
#   aws configure   (or export AWS_PROFILE)
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/_build"
AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export AWS_DEFAULT_REGION

ALL_AGENTS=("ai-gk" "ai-def1" "ai-def2" "ai-mid" "ai-fwd")
if [ -n "$1" ]; then AGENTS=("$1"); else AGENTS=("${ALL_AGENTS[@]}"); fi

echo "Checking prerequisites..."
for tool in agentcore aws rsync; do
  command -v "$tool" >/dev/null || {
    echo "ERROR: '$tool' not found."
    [ "$tool" = "agentcore" ] && echo "  Install: pip install bedrock-agentcore-starter-toolkit"
    exit 1; }
done

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
  echo "ERROR: no valid AWS credentials."; exit 1; }
export AWS_ACCOUNT_ID
echo "  account $AWS_ACCOUNT_ID / region $AWS_DEFAULT_REGION"

trap 'rm -rf "$BUILD_DIR"' EXIT
rm -rf "$BUILD_DIR"

bake_env() {                       # $1 = staging dir
  {
    echo "# Generated by deploy-all.sh. Do not edit; re-deploy to change."
    echo "SETTINGS = {"
    for var in AFC_USE_LLM AFC_MODEL_ID AFC_MODEL_GK AFC_MODEL_DEFENDER \
               AFC_MODEL_MIDFIELDER AFC_MODEL_FORWARD AFC_REGION \
               AFC_LLM_DEADLINE AFC_ANALYSIS AFC_MEMORY AFC_SCOUTING \
               AFC_GATEWAY_URL AFC_GATEWAY_TOKEN AFC_TACTICS; do
      value="${!var-}"
      [ -n "$value" ] && printf '    %s: %s,\n' "\"$var\"" \
        "$(printf '%s' "$value" | python3 -c 'import sys;print(repr(sys.stdin.read()))')"
    done
    echo "}"
  } > "$1/afc_env.py"
}

DEPLOYED=(); FAILED=()
for agent in "${AGENTS[@]}"; do
  SRC="$SCRIPT_DIR/agents/$agent"
  STAGE="$BUILD_DIR/$agent"
  echo ""
  echo "=== $agent ==="
  if [ ! -d "$SRC" ]; then
    echo "  ERROR: no such agent: $SRC"; FAILED+=("$agent"); continue
  fi

  mkdir -p "$STAGE/src"
  cp "$SRC/src/main.py" "$STAGE/src/main.py"
  rsync -a --exclude='__pycache__' "$SCRIPT_DIR/lib/" "$STAGE/lib/"
  cp "$SRC/requirements.txt" "$STAGE/requirements.txt"
  bake_env "$STAGE"
  sed -e "s|\${AWS_ACCOUNT_ID}|$AWS_ACCOUNT_ID|g" \
      -e "s|\${AWS_DEFAULT_REGION}|$AWS_DEFAULT_REGION|g" \
      "$SRC/.bedrock_agentcore.yaml.template" > "$STAGE/.bedrock_agentcore.yaml"

  if (cd "$STAGE" && agentcore deploy --auto-update-on-conflict); then
    echo "  OK   $agent"; DEPLOYED+=("$agent")
  else
    echo "  FAIL $agent"; FAILED+=("$agent")
  fi
done

echo ""
echo "=========================================="
echo "  deployed: ${DEPLOYED[*]:-none}"
echo "  failed:   ${FAILED[*]:-none}"
echo "=========================================="
[ ${#FAILED[@]} -gt 0 ] && exit 1
# A deployed version does NOT reach an existing session: AgentCore pins a
# runtimeSessionId to the container that was live when the session started, and
# the platform reuses one long-lived session per slot. Without this step the
# competition keeps running the PREVIOUS build while every hand-made probe runs
# the new one - a fixed bug that still fails the fitness check. See
# stop_stale_sessions.py.
echo ""
echo "Stopping stale platform sessions so this deploy actually takes effect..."
if ! python3 "$SCRIPT_DIR/stop_stale_sessions.py" --minutes 120; then
  echo "  WARNING: could not stop sessions - the platform may still be running"
  echo "           the previous build. Run stop_stale_sessions.py by hand."
fi

echo ""
echo "Register these ARNs with the platform, one per player index:"
for a in "${DEPLOYED[@]}"; do
  case "$a" in
    ai-gk)   idx=0; rt=afc_gk_agent   ;;
    ai-def1) idx=1; rt=afc_def1_agent ;;
    ai-def2) idx=2; rt=afc_def2_agent ;;
    ai-mid)  idx=3; rt=afc_mid_agent  ;;
    ai-fwd)  idx=4; rt=afc_fwd_agent  ;;
  esac
  echo "  player $idx  arn:aws:bedrock-agentcore:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:runtime/$rt"
done
