#!/bin/bash
set -e

# ============================================================================
# Deploy the agent to Amazon Bedrock AgentCore Runtime.
#
#   AWS_DEFAULT_REGION=us-east-1 ./deploy.sh
#
# Staging keeps lib/ a single source of truth: it is copied into _build/ at
# deploy time rather than duplicated into the runtime tree.
#
# Prerequisites:
#   pip install bedrock-agentcore-starter-toolkit
#   aws configure   (or export AWS_PROFILE)
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BUILD_DIR="$SCRIPT_DIR/_build"

AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export AWS_DEFAULT_REGION

echo "Checking prerequisites..."
for tool in agentcore aws rsync; do
  if ! command -v "$tool" &> /dev/null; then
    echo "ERROR: '$tool' not found."
    [ "$tool" = "agentcore" ] && echo "  Install: pip install bedrock-agentcore-starter-toolkit"
    exit 1
  fi
done

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
  echo "ERROR: no valid AWS credentials."
  exit 1
}
export AWS_ACCOUNT_ID
echo "  account $AWS_ACCOUNT_ID / region $AWS_DEFAULT_REGION"

cleanup() { rm -rf "$BUILD_DIR"; }
trap cleanup EXIT

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

cp "$SCRIPT_DIR/runtime/main.py" "$BUILD_DIR/main.py"
rsync -a --exclude='__pycache__' "$SCRIPT_DIR/lib/" "$BUILD_DIR/lib/"
cp "$SCRIPT_DIR/requirements-runtime.txt" "$BUILD_DIR/requirements.txt"

# Bake the AFC_* settings into the bundle. AgentCore does not carry the
# deploying shell's environment into the running agent, so without this every
# model choice, deadline and feature flag reverts to its built-in default the
# moment it is deployed - silently, and only visible in the match result.
{
  echo "# Generated by deploy.sh. Do not edit; re-deploy to change."
  echo "SETTINGS = {"
  for var in AFC_USE_LLM AFC_MODEL_ID AFC_MODEL_GK AFC_MODEL_DEFENDER \
             AFC_MODEL_MIDFIELDER AFC_MODEL_FORWARD AFC_REGION \
             AFC_LLM_DEADLINE AFC_ANALYSIS AFC_MEMORY AFC_SCOUTING AFC_TACTICS; do
    value="${!var-}"
    [ -n "$value" ] && printf '    %s: %s,\n' "\"$var\"" "$(printf '%s' "$value" | python3 -c 'import sys;print(repr(sys.stdin.read()))')"
  done
  echo "}"
} > "$BUILD_DIR/afc_env.py"
echo "Baked settings:"
sed -n '3,$p' "$BUILD_DIR/afc_env.py" | sed 's/^/  /'

sed \
  -e "s|\${AWS_ACCOUNT_ID}|$AWS_ACCOUNT_ID|g" \
  -e "s|\${AWS_DEFAULT_REGION}|$AWS_DEFAULT_REGION|g" \
  "$SCRIPT_DIR/runtime/.bedrock_agentcore.yaml.template" > "$BUILD_DIR/.bedrock_agentcore.yaml"

echo "Deploying from $BUILD_DIR ..."
(cd "$BUILD_DIR" && agentcore deploy --auto-update-on-conflict)

echo ""
echo "Deployed. Point a team file at the runtime ARN:"
echo ""
echo "  agent:"
echo "    transport: agentcore"
echo "    runtime_arn: arn:aws:bedrock-agentcore:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:runtime/afc_contender"
echo "    region: $AWS_DEFAULT_REGION"
