#!/bin/bash
set -e
# pipefail matters here: the deploy is piped through sed to prefix its output,
# and without it the pipeline reports sed's exit status, so a FAILED deploy
# would be announced as OK.
set -o pipefail

# ============================================================================
# Deploy ONE agent. Safe to run five of these at the same time.
#
#   ./deploy-one.sh ai-mid
#
# Concurrency notes — these are why this is a separate script and not just
# deploy-all.sh with an argument:
#   * Staging is per agent (_build/<agent>) and this script only ever removes
#     its OWN directory. The previous script wiped all of _build/ on entry and
#     again from an EXIT trap, so the first sibling to finish deleted the
#     staging of the four still running.
#   * The stale-session sweep is NOT done here. It is global, and running it
#     five times over would race with the deploys still in flight. deploy-all.sh
#     does it once after the fan-out; run stop_stale_sessions.py yourself if you
#     deploy a single agent by hand.
#   * Every line is prefixed with the agent name, because parallel output
#     interleaves and unlabelled progress from five deploys is unreadable.
#
# AFC_* settings are baked into the bundle: a deployed runtime does NOT inherit
# the shell that deployed it, so anything exported here would otherwise revert
# to defaults, silently.
# ============================================================================

AGENT="${1:-}"
if [ -z "$AGENT" ]; then
  echo "usage: $0 <agent>   (ai-gk | ai-def1 | ai-def2 | ai-mid | ai-fwd)" >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SRC="$SCRIPT_DIR/agents/$AGENT"
STAGE="$SCRIPT_DIR/_build/$AGENT"
AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export AWS_DEFAULT_REGION

say() { echo "[$AGENT] $*"; }

[ -d "$SRC" ] || { say "ERROR: no such agent: $SRC"; exit 1; }

for tool in agentcore aws rsync; do
  command -v "$tool" >/dev/null || {
    say "ERROR: '$tool' not found."
    [ "$tool" = "agentcore" ] && say "  pip install bedrock-agentcore-starter-toolkit"
    exit 1; }
done

# Callers that already resolved the account pass it in, so five parallel
# deploys do not make five identical sts calls.
if [ -z "${AWS_ACCOUNT_ID:-}" ]; then
  AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text 2>/dev/null) || {
    say "ERROR: no valid AWS credentials."; exit 1; }
fi
export AWS_ACCOUNT_ID

# Only ever our own directory, never the shared parent.
trap 'rm -rf "$STAGE"' EXIT
rm -rf "$STAGE"
mkdir -p "$STAGE/src"

cp "$SRC/src/main.py" "$STAGE/src/main.py"
rsync -a --exclude='__pycache__' "$SCRIPT_DIR/lib/" "$STAGE/lib/"
cp "$SRC/requirements.txt" "$STAGE/requirements.txt"

{
  echo "# Generated by deploy-one.sh. Do not edit; re-deploy to change."
  echo "SETTINGS = {"
  for var in AFC_USE_LLM AFC_MODEL_ID AFC_MODEL_GK AFC_MODEL_DEFENDER \
             AFC_MODEL_MIDFIELDER AFC_MODEL_FORWARD AFC_REGION \
             AFC_LLM_DEADLINE AFC_ANALYSIS AFC_MEMORY AFC_SCOUTING \
             AFC_GATEWAY_URL AFC_GATEWAY_TOKEN AFC_TACTICS; do
    value="${!var-}"
    [ -n "$value" ] && printf '    %s: %s,\n' "\"$var\"" \
      "$(printf '%s' "$value" | python3 -c 'import sys;print(repr(sys.stdin.read()))')"
  done
  echo "}"
} > "$STAGE/afc_env.py"

sed -e "s|\${AWS_ACCOUNT_ID}|$AWS_ACCOUNT_ID|g" \
    -e "s|\${AWS_DEFAULT_REGION}|$AWS_DEFAULT_REGION|g" \
    "$SRC/.bedrock_agentcore.yaml.template" > "$STAGE/.bedrock_agentcore.yaml"

say "deploying..."
if (cd "$STAGE" && agentcore deploy --auto-update-on-conflict) 2>&1 | sed "s/^/[$AGENT] /"; then
  say "OK"
  exit 0
else
  say "FAILED"
  exit 1
fi
